### ISSUE TITLE
Reproducing results

### ISSUE THREAD

**Issue by j-c-carr** [jantiegges/comp550-final#1]

**Comment by j-c-carr** [comment]
Tried reproducing results using the functions in `main.py`. I am getting the following error:

```
config.json: 100%|██████████| 891/891 [00:00<00:00, 76.4kB/s]
model.safetensors: 100%|██████████| 711M/711M [00:19<00:00, 37.1MB/s]
tokenizer_config.json: 100%|██████████| 407/407 [00:00<00:00, 28.3kB/s]
vocab.txt: 100%|██████████| 996k/996k [00:00<00:00, 8.02MB/s]
special_tokens_map.json: 100%|██████████| 112/112 [00:00<00:00, 35.8kB/s]
Attempting to initialize pre-built index miracl-v1.0-en-mdpr-tied-pft-msmarco.
Downloading index at https://rgw.cs.uwaterloo.ca/pyserini/indexes/faiss.miracl-v1.0-en.mdpr-tied-pft-msmarco.20221004.2b2856.tar.gz...
faiss.miracl-v1.0-en.mdpr-tied-pft-msmarco.20221004.2b2856.tar.gz: 87.1GB [46:51, 33.3MB/s]                            
Extracting /home/jcc/.cache/pyserini/indexes/faiss.miracl-v1.0-en.mdpr-tied-pft-msmarco.20221004.2b2856.tar.gz into /home/jcc/.cache/pyserini/indexes/faiss.miracl-v1.0-en.mdpr-tied-pft-msmarco.20221004.2b2856.ce00518f54b130a157112c2a1b2d0980...
Initializing miracl-v1.0-en-mdpr-tied-pft-msmarco...
Traceback (most recent call last):
  File "/home/jcc/Documents/msc/courses/c550/comp550-final/main.py", line 46, in <module>
    searcher = FaissSearcher.from_prebuilt_index(
  File "/home/jcc/Documents/msc/courses/c550/comp550-final/venv/lib/python3.8/site-packages/pyserini/search/faiss/_searcher.py", line 435, in from_prebuilt_index
    return cls(index_dir, query_encoder, prebuilt_index_name)
  File "/home/jcc/Documents/msc/courses/c550/comp550-final/venv/lib/python3.8/site-packages/pyserini/search/faiss/_searcher.py", line 395, in __init__
    self.index, self.docids = self.load_index(index_dir)
  File "/home/jcc/Documents/msc/courses/c550/comp550-final/venv/lib/python3.8/site-packages/pyserini/search/faiss/_searcher.py", line 539, in load_index
    index = faiss.read_index(index_path)
  File "/home/jcc/Documents/msc/courses/c550/comp550-final/venv/lib/python3.8/site-packages/faiss/swigfaiss_avx2.py", line 10206, in read_index
    return _swigfaiss_avx2.read_index(*args)
MemoryError: std::bad_alloc
```

**Next steps:**
* Try with a different dataset (e.g. French) to see if the error persists
* Try reproducing the results using the commands on the pyserini website [(link)](https://castorini.github.io/pyserini/2cr/miracl.html)

**Comment by j-c-carr** [comment]
I tried to reproduce the Miracl results for the French dataset using [the pyserini command lineinstructions](https://castorini.github.io/pyserini/2cr/miracl.html). As with the English dataset, I can reproduce the BM-25 results but I'm getting a similar memory error for mDPR:
```
(venv) jcc:comp550-final python -m pyserini.search.faiss \
>   --threads 16 --batch-size 512 \
>   --encoder-class auto \
>   --encoder castorini/mdpr-tied-pft-msmarco \
>   --topics miracl-v1.0-fr-dev \
>   --index miracl-v1.0-fr-mdpr-tied-pft-msmarco \
>   --output run.miracl.mdpr-tied-pft-msmarco.fr.dev.txt --hits 1000
/home/jcc/Documents/msc/courses/c550/comp550-final/venv/lib/python3.8/site-packages/torch/cuda/__init__.py:138: UserWarning: CUDA initialization: The NVIDIA driver on your system is too old (found version 11040). Please update your GPU driver by downloading and installing a new version from the URL: http://www.nvidia.com/Download/index.aspx Alternatively, go to: https://pytorch.org to install a PyTorch version that has been compiled with your version of the CUDA driver. (Triggered internally at ../c10/cuda/CUDAFunctions.cpp:108.)
  return torch._C._cuda_getDeviceCount() > 0
Attempting to initialize pre-built index miracl-v1.0-fr-mdpr-tied-pft-msmarco.
Downloading index at https://rgw.cs.uwaterloo.ca/pyserini/indexes/faiss.miracl-v1.0-fr.mdpr-tied-pft-msmarco.20221004.2b2856.tar.gz...
faiss.miracl-v1.0-fr.mdpr-tied-pft-msmarco.20221004.2b2856.tar.gz: 38.8GB [24:42, 28.1MB/s]                                                               
Extracting /home/jcc/.cache/pyserini/indexes/faiss.miracl-v1.0-fr.mdpr-tied-pft-msmarco.20221004.2b2856.tar.gz into /home/jcc/.cache/pyserini/indexes/faiss.miracl-v1.0-fr.mdpr-tied-pft-msmarco.20221004.2b2856.a952d944aa63dcee604c8357f1be18db...
Initializing miracl-v1.0-fr-mdpr-tied-pft-msmarco...
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/jcc/Documents/msc/courses/c550/comp550-final/venv/lib/python3.8/site-packages/pyserini/search/faiss/__main__.py", line 205, in <module>
    searcher = FaissSearcher.from_prebuilt_index(args.index, query_encoder)
  File "/home/jcc/Documents/msc/courses/c550/comp550-final/venv/lib/python3.8/site-packages/pyserini/search/faiss/_searcher.py", line 435, in from_prebuilt_index
    return cls(index_dir, query_encoder, prebuilt_index_name)
  File "/home/jcc/Documents/msc/courses/c550/comp550-final/venv/lib/python3.8/site-packages/pyserini/search/faiss/_searcher.py", line 395, in __init__
    self.index, self.docids = self.load_index(index_dir)
  File "/home/jcc/Documents/msc/courses/c550/comp550-final/venv/lib/python3.8/site-packages/pyserini/search/faiss/_searcher.py", line 539, in load_index
    index = faiss.read_index(index_path)
  File "/home/jcc/Documents/msc/courses/c550/comp550-final/venv/lib/python3.8/site-packages/faiss/swigfaiss_avx2.py", line 10206, in read_index
    return _swigfaiss_avx2.read_index(*args)
MemoryError: std::bad_alloc
```
For both datasets, the problem seems to be a memory error when `Initializing miracl-v1.0-[fr/en]-mdpr-tied-pft-msmarco`.

I still have lots of disk space (>160Gb) so I don't think the problem is disk memory. For the French dataset, the last file downloaded before the error is `faiss.miracl-v1.0-fr.mdpr-tied-pft-msmarco.20221004.2b2856.tar.gz` is around 38Gb. For the English dataset, the last file downloaded before the memory error is `faiss.miracl-v1.0-en.mdpr-tied-pft-msmarco.20221004.2b2856.tar.gz`, which is around 86Gb. 

**Next Steps**
* The Miracl datasets do not seem feasible, so I am going to try to reproduce results on smaller datasets

**Comment by j-c-carr** [comment]
I get the same memory errors for `MS Marco V1 Passage` and `Mr.TyDi` for mDPR.

**Comment by j-c-carr** [comment]
Closing this issue because it seems intractable in the given time frame to compute mDPR or hybrid baselines. Since we are able to perfectly reproduce metrics for BM25 the baselines, I suggest that we just cite the scores for the mDPR and Hybrid methods.
